FROM ghcr.io/usace-cloud-compute/cc-tiledb-base:latest as dev

ENV PATH="/gradle/bin:${PATH}"
ENV TILEDB_HOME=/usr/local/lib/tiledb

RUN apt update -y &&\
    apt install openjdk-21-jdk -y

RUN cd /opt/tiledb &&\
    git clone https://github.com/TileDB-Inc/TileDB-Java.git &&\
    cd TileDB-Java &&\
    git checkout 0.30.0 &&\
    ./gradlew build -x test

